#include "query/query.h"
#include "core/string_util.h"
#include "core/time.h"
#include <cctype>

namespace logharbor::query {
std::vector<Token> lex(const std::string& q){ std::vector<Token> t; for(std::size_t i=0;i<q.size();){ if(std::isspace(static_cast<unsigned char>(q[i]))){++i;continue;} if(q[i]=='('||q[i]==')'){t.push_back({std::string(1,q[i]),std::string(1,q[i])});++i;continue;} if(i+1<q.size()&&(q.substr(i,2)=="=="||q.substr(i,2)=="!="||q.substr(i,2)==">="||q.substr(i,2)=="<=")){ t.push_back({"op",q.substr(i,2)}); i+=2; continue;} if(q[i]=='='||q[i]=='~'||q[i]=='>'||q[i]=='<'){t.push_back({"op",std::string(1,q[i])});++i;continue;} if(q[i]=='"'){std::string v; ++i; while(i<q.size()&&q[i]!='"'){ if(q[i]=='\\'&&i+1<q.size())++i; v.push_back(q[i++]); } if(i<q.size())++i; t.push_back({"word",v}); continue;} std::size_t j=i; while(j<q.size()&&!std::isspace(static_cast<unsigned char>(q[j]))&&q[j]!='('&&q[j]!=')'&&q[j]!='='&&q[j]!='~'&&q[j]!='<'&&q[j]!='>')++j; std::string w=q.substr(i,j-i); auto lw=core::lower(w); t.push_back((lw=="and"||lw=="or"||lw=="not")?Token{lw,lw}:Token{"word",w}); i=j;} return t; }
namespace {
class TrueExpr: public Expression{ bool eval(const ingest::Event&) const override{return true;} };
class NotExpr: public Expression{ ExprPtr a_; public: explicit NotExpr(ExprPtr a):a_(std::move(a)){} bool eval(const ingest::Event& e) const override{return !a_->eval(e);} };
class BinaryExpr: public Expression{ std::string op_; ExprPtr l_,r_; public: BinaryExpr(std::string o,ExprPtr l,ExprPtr r):op_(std::move(o)),l_(std::move(l)),r_(std::move(r)){} bool eval(const ingest::Event& e) const override{return op_=="and"?(l_->eval(e)&&r_->eval(e)):(l_->eval(e)||r_->eval(e));} };
class CompareExpr: public Expression{ std::string f_,op_,v_; public: CompareExpr(std::string f,std::string o,std::string v):f_(core::normalize_field_name(f)),op_(std::move(o)),v_(std::move(v)){} bool eval(const ingest::Event& e) const override{ auto got=e.field(f_); if(op_=="="||op_=="==")return got==v_; if(op_=="!=")return got!=v_; if(op_=="~")return core::contains_case_insensitive(got,v_); std::int64_t a=0,b=0; if(core::parse_i64(got,a)&&core::parse_i64(v_,b)){ if(op_==">")return a>b; if(op_=="<")return a<b; if(op_==">=")return a>=b; if(op_=="<=")return a<=b;} return false;} };
class Parser{ std::vector<Token> t_; std::size_t p_{0}; public: Parser(std::vector<Token> t):t_(std::move(t)){} bool at(const std::string& k)const{return p_<t_.size()&&t_[p_].kind==k;} bool text(const std::string& s)const{return p_<t_.size()&&core::lower(t_[p_].text)==s;} Token take(){return p_<t_.size()?t_[p_++]:Token{"",""};} ExprPtr primary(){ if(text("not")){take();return ExprPtr(new NotExpr(primary()));} if(at("(")){take();auto e=expr(); if(at(")"))take(); return e;} if(p_+2<t_.size()&&t_[p_].kind=="word"&&t_[p_+1].kind=="op"){auto f=take().text;auto o=take().text;auto v=take().text;return ExprPtr(new CompareExpr(f,o,v));} if(p_<t_.size()){auto w=take().text;return ExprPtr(new CompareExpr("message","~",w));} return ExprPtr(new TrueExpr());} ExprPtr conj(){auto l=primary(); while(text("and")){take();l=ExprPtr(new BinaryExpr("and",std::move(l),primary()));} return l;} ExprPtr expr(){auto l=conj(); while(text("or")){take();l=ExprPtr(new BinaryExpr("or",std::move(l),conj()));} return l;} };
}
core::Result<ExprPtr> parse(const std::string& q){ auto t=lex(q); if(t.empty()) return core::Result<ExprPtr>::success(ExprPtr(new TrueExpr())); Parser p(std::move(t)); return core::Result<ExprPtr>::success(p.expr()); }
bool matches(const ingest::Event& e,const std::string& q){ auto r=parse(q); return r ? r.value()->eval(e) : false; }
std::vector<ingest::Event> filter(const std::vector<ingest::Event>& events,const std::string& q){ auto r=parse(q); std::vector<ingest::Event> out; if(!r)return out; for(const auto& e:events)if(r.value()->eval(e))out.push_back(e); return out; }
}
